"use strict";

/**
 * Layer 4 — Supplier Purchase Order Generator.
 *
 * Turns the product insights engine's restock advice (or any explicit
 * item list) into a formatted purchase order the client can send to
 * their supplier. Generated POs are persisted for the audit trail.
 */

function createPurchaseOrderGenerator({ store, productInsights }) {
  /** Render a PO as plain-text document (swap for PDF generation later). */
  function renderDocument(po) {
    const lines = [
      "PURCHASE ORDER",
      "==============",
      `PO Number:   ${po.po_number}`,
      `Store:       ${po.store_id}`,
      `Supplier:    ${po.supplier}`,
      `Date:        ${po.created_at.slice(0, 10)}`,
      "",
      "ITEMS",
      "-----",
      ...po.items.map(
        (item, index) =>
          `${index + 1}. ${item.product_id} — ${item.quantity} unit(s)` +
          (item.reason ? `   (${item.reason})` : "")
      ),
      "",
      `Total units: ${po.total_units}`,
      "",
      "Generated by Storecops Growth Platform — restock advice based on",
      "live sales velocity, stock cover and supplier lead times.",
    ];
    return lines.join("\n");
  }

  return {
    /**
     * Build a PO from the current restock_urgent list (default) or an
     * explicit items array: [{ product_id, quantity }].
     */
    async generate({ store_id, supplier = "Primary Supplier", items = null, windowDays = 30 } = {}) {
      if (!store_id) throw new Error("store_id is required.");

      let lines = items;
      if (!lines) {
        const insights = await productInsights.analyze(store_id, windowDays);
        lines = insights.restock_urgent.map((entry) => ({
          product_id: entry.product_id,
          quantity: entry.suggested_qty,
          reason: entry.severity,
        }));
      }

      lines = lines
        .filter((item) => item.product_id && item.quantity > 0)
        .map((item) => ({
          product_id: item.product_id,
          quantity: Math.ceil(item.quantity),
          reason: item.reason || null,
        }));

      if (lines.length === 0) {
        return { store_id, po: null, message: "Nothing needs reordering right now." };
      }

      const po = await store.purchaseOrders.insert({
        po_number: `PO-${store_id}-${Date.now().toString(36).toUpperCase()}`,
        store_id,
        supplier,
        items: lines,
        total_units: lines.reduce((sum, item) => sum + item.quantity, 0),
        status: "DRAFT",
        created_at: new Date().toISOString(),
      });

      return { store_id, po: { ...po, document: renderDocument(po) } };
    },

    /** Previously generated POs. */
    async list(store_id, limit = 10) {
      const pos = await store.purchaseOrders.find({ store_id });
      return pos.sort((a, b) => b.created_at.localeCompare(a.created_at)).slice(0, limit);
    },
  };
}

module.exports = { createPurchaseOrderGenerator };
